### ISSUE TITLE
Processing error: 'Queue' object has no attribute 'size'

### ISSUE THREAD

**Issue by gemblerz** [epics-base/pvaPy#94]
Hello!

I am testing the streaming feature by constructing a pipeline as,

```bash
[ ad-sim-server ] ---- [ mirror-server ] ---- [ hpc-consumer ]
```
I am using pvapy == 5.3.1 for all of the components above,
```bash
root@consumer-77588f84c6-8gwdw:~# pip3 show pvapy
Name: pvapy
Version: 5.3.1
Summary: Python library for EPICS PV Access
Home-page: https://github.com/epics-base/pvaPy
Author: 
Author-email: 
License: EPICS Open License
Location: /usr/local/lib/python3.10/dist-packages
Requires: numpy
Required-by: 
```

Each component is a container running in a Kubernetes cluster, and configurations for each of them are,
- ad-sim-server
```yaml
...
    command: ["pvapy-ad-sim-server"]
    args:
    - --channel-name
    - ad:image
    - --n-x-pixels
    - "512"
    - --n-y-pixels
    - "512"
    - --datatype
    - int16
    - --frame-rate
    - "100"
    - --runtime
    - "400"
    - --disable-curses
... 
```
- mirror-server
```yaml
...
        command: ["pvapy-mirror-server"]
        args:
        - --channel-map
        - "(pvapy:image,ad:image,pva,20000)"
 ...
```

- hpc-consumer
```yaml
...
        command: ["pvapy-hpc-consumer"]
        args:
        - -ll
        - "error"
        - --input-channel
        - "pvapy:image"
        - --consumer-id
        - "1"
        - --control-channel
        - "processor:*:control"
        - --status-channel
        - "processor:*:status"
        - --output-channel
        - "processor:*:output"
        - --processor-file
        - "/app/inferPtychoNNImageProcessor.py"
        - --processor-class
        - "InferPtychoNNImageProcessor"
        - --processor-args
        - '{"onnx_mdl": "/app/model_512_fp16.trt", "output_x": 64, "output_y": 64, "net": "wan0"}'
        - --report-period
        - "5"
        - --n-consumers
        - "1"
        - --server-queue-size
        - "100"
        - --monitor-queue-size
        - "1000"
        - --distributor-updates
        - "8"
        - --disable-curses
...
```

**Problem**: I expected the hpc-consumer would process incoming frames but it outputted the following error repeatedly, as data comes from the prior components,
```bash
...
DataConsumerController ERROR: Processing error: 'Queue' object has no attribute 'size'
...
```

Can you help me find where to start for debugging this?
